### ISSUE TITLE
ROS driver and compatibility ?

### ISSUE THREAD

**Issue by zlg9folira** [sparkfun/Qwiic_9DoF_IMU_ICM20948_Py#3]
Two questions: 
1- Is this particular IMU compatible with this Sparkfun ROS driver http://wiki.ros.org/razor_imu_9dof ? I need the IMU data in the form of `/Sensor_msgs/IMU` topic.
2- How does this IMU connect to USB on computer? What particular adapter will work?

**Comment by santaimpersonator** [comment]
I am closing this issue as it has nothing to do with the Python package.

- This repo is for a Python package. You are looking for this retired product: https://www.sparkfun.com/products/retired/14001
- Please use our [forum](https://forum.sparkfun.com/) for technical assistance.
